
typedef enum _SESSION_STATE
{
    SESSION_STATE_OFFLINE_IDLE = 0,
    SESSION_STATE_OFFLINE_WAIT,
    SESSION_STATE_ONLINE_IDLE,
    SESSION_STATE_ONLINE_REPLY,
    SESSION_STATE_ONLINE_WAIT
} SESSION_STATE;

